obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
#ifdef VENDOR_EDIT /* lizhijie@BSP.CHG.Basic, 2020/03/25, Add for charging */
obj-$(CONFIG_OPLUS_CHARGER)	+= oplus/
#endif
