#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# Jun.Liang@MULTIMEDIA.AUDIODRIVER.MACHINE, 2020/08/26, Add for oplus extend audio
obj-y += driver/
# Zhao.Pan@MULTIMEDIA.AUDIODRIVER.SMARTPA, 2020/04/28, add for aw87339 PA
# obj-y += aw87339/
# Jingjing.Jiang@MULTIMEDIA.AUDIODRIVER.SMARTPA, 2020/05/19, add for tfa98xx smartPA
obj-y += tfa98xx/
# Jun.Liang@MULTIMEDIA.AUDIODRIVER.SMARTPA, 2020/09/08, add for SIA PA ALGO
obj-$(CONFIG_SIA_PA_ALGO) += sia81xx/
# sidong.Zhao@WT,2021/3/9,for AWINIC AW889X Smart K PA
obj-$(CONFIG_SND_SOC_AW87XXX) += awinic/
